C:\Python34\python.exe "C:\SteamLibrary\SteamApps\common\dota 2 beta\game\dota_addons\trails\make_npc_abilities_custom.py"
C:\Python34\python.exe "C:\SteamLibrary\SteamApps\common\dota 2 beta\game\dota_addons\trails\make_npc_heroes_custom.py"
C:\Python34\python.exe "C:\SteamLibrary\SteamApps\common\dota 2 beta\game\dota_addons\trails\make_npc_units_custom.py"
C:\Python34\python.exe "C:\SteamLibrary\SteamApps\common\dota 2 beta\game\dota_addons\trails\generatequartzkv.py"
C:\Python34\python.exe "C:\SteamLibrary\SteamApps\common\dota 2 beta\game\dota_addons\trails\make_npc_items_custom.py"
C:\Python34\python.exe "C:\SteamLibrary\SteamApps\common\dota 2 beta\game\dota_addons\trails\generatetooltips.py"
C:\Python34\python.exe "C:\SteamLibrary\SteamApps\common\dota 2 beta\game\dota_addons\trails\generatemasterquartztooltips.py"
C:\Python34\python.exe "C:\SteamLibrary\SteamApps\common\dota 2 beta\game\dota_addons\trails\make_addon_english.py"